package com.groupb.rental.dao;

import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import com.groupb.rental.model.Booking;
import com.groupb.rental.model.Vehicle;

/**
 * Tests for the BookingDAO functionalities.
 * Verifies that bookings can be added and that they can be retrieved by user.
 */
public class BookingDAOTest {

    // DAO for bookings and vehicles are declared for use in tests.
    private BookingDAOInterface bookingDAO;
    private VehicleDAOInterface vehicleDAO; 

    /**
     * The setUp() method is run before each test.
     * It initializes the DAO implementations used in the tests.
     */
    @Before
    public void setUp() {
        bookingDAO = new BookingDAOImpl();
        vehicleDAO = new VehicleDAOImpl();
    }

    /**
     * Helper method to create and insert a test vehicle.
     * It returns the id of the vehicle inserted so it can be used in booking tests.
     *
     * @return The id of the newly inserted test vehicle.
     */
    private int createTestVehicle() {
        Vehicle vehicle = new Vehicle();
        vehicle.setId(0); // id will be auto-generated by database if applicable
        vehicle.setType("Car");
        vehicle.setBrand("Toyota");
        vehicle.setModel("Camry");
        vehicle.setPricePerDay(50.0);
        vehicle.setAvailable(true);
        vehicleDAO.addVehicle(vehicle);
        // Retrieve the list of vehicles and return the id of the last one inserted
        List<Vehicle> vehicles = vehicleDAO.getAllVehicles();
        return vehicles.get(vehicles.size() - 1).getId();
    }

    /**
     * Tests that a booking can be added successfully.
     * This test creates a test vehicle first, then builds a Booking object
     * and attempts to add it via the BookingDAO.
     */
    @Test
    public void testAddBooking() throws Exception {
        int validVehicleId = createTestVehicle();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date bookingDate = sdf.parse("2025-04-01");
        Date returnDate = sdf.parse("2025-04-05");

        Booking booking = new Booking();
        booking.setId(0); // id should be auto-generated if applicable
        booking.setUserId(1); // using 1 as a test user id
        booking.setVehicleId(validVehicleId);  // Set to valid vehicle id from helper method
        booking.setBookingDate(bookingDate);
        booking.setReturnDate(returnDate);
        booking.setTotalCost(200.0);
        booking.setStatus("pending");

        // Assert that adding the booking returns true
        boolean success = bookingDAO.addBooking(booking);
        assertTrue("Booking should be added successfully", success);
    }

    /**
     * Tests that the DAO returns bookings for a specific user.
     * This test first inserts a booking, then retrieves the booking list for user id 1.
     */
    @Test
    public void testGetBookingsByUser() throws Exception {
        int validVehicleId = createTestVehicle();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date bookingDate = sdf.parse("2025-04-01");
        Date returnDate = sdf.parse("2025-04-05");

        Booking booking = new Booking();
        booking.setId(0);
        booking.setUserId(1);
        booking.setVehicleId(validVehicleId);
        booking.setBookingDate(bookingDate);
        booking.setReturnDate(returnDate);
        booking.setTotalCost(200.0);
        booking.setStatus("pending");

        // First add the booking
        boolean added = bookingDAO.addBooking(booking);
        assertTrue("Booking should be added", added);

        // Then, retrieve bookings for user with id 1 and validate the results
        List<Booking> bookings = bookingDAO.getBookingsByUser(1);
        assertNotNull("Booking list should not be null", bookings);
        assertTrue("Booking list should have at least one booking", bookings.size() > 0);
    }
}
